# Generated by Django 4.0.4 on 2022-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resenia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
